# Generated by Django 4.1.4 on 2022-12-26 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_alter_profile_follower_alter_profile_following_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="follower"),
        migrations.RemoveField(model_name="profile", name="following"),
        migrations.AddField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
